A = int(input('Введите число: '))
B = int(input('Введите число: '))
print(f"{A} + {B} = {A+B}")
print(f"{A} - {B} = {A-B}")
print(f"{A} * {B} = {A*B}")
print(f"{A} / {B} = {A/B}")
print(f"{A} ** {B} = {A**B}")
print(f"{A} % {B} = {A%B}")
